name: Download Docker Image
on: [workflow_dispatch]

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Images
        run: |
          # 拉取四个监控组件的最新版
          docker pull prom/blackbox-exporter
          
          # 打包保存（文件名加上latest标识）
          docker save -o monitor_images_latest.tar prom/blackbox-exporter
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: monitor_images_latest
          path: monitor_images_latest.tar
